language: c

sudo: required
dist: xenial

addons:
  apt:
    packages:
    - libsnappy1v5
    - libsnappy-dev
    - libleveldb-dev
    - librrd-dev
    - libxslt1-dev
    - libssl-dev
    - libffi-dev
    - libc-ares-dev
    - libc-ares2

before_install:
  - sudo apt-get -y install python2.7/xenial python2.7-dev/xenial python2.7-minimal/xenial libpython2.7/xenial libpython2.7-dev/xenial libpython2.7-minimal/xenial libpython2.7-stdlib/xenial
  - export PATH=/usr/bin:$PATH

install:
  - sudo -H pip install --upgrade pip
  - sudo -H pip install -r requirements-dev.txt

script:
  - /usr/bin/env python -V
  - platter build -r requirements-web.txt --prebuild-script scripts/prebuild-script.sh

deploy:
  provider: s3
  access_key_id: "$S3_ACCESS_KEY"
  secret_access_key: "$S3_SECRET_ACCESS_KEY"
  bucket: "minemeld"
  skip_cleanup: true
  local_dir: dist
  acl: public_read
  on:
    tags: true

after_deploy:
    - "export FILENAME=minemeld-core-$TRAVIS_TAG-linux-x86_64.tar.gz"
    - "export MD5SUM=$(md5sum dist/$FILENAME | awk '{ print $1 }')"
    - "export SHA256SUM=$(sha256sum dist/$FILENAME | awk '{ print $1 }')"
    - "echo $MD5SUM"
    - "echo $SHA256SUM"
